
### 회원가입
POST http://nodeapi.myspaceti.me:8001/api/signup
Content-Type: application/json

{  
    "nickname": "Tester8",  
    "password": "12345",  
    "confirm": "12345"
}
    
### 로그인
POST http://nodeapi.myspaceti.me:8000/api/login
Content-Type: application/json

{  
    "nickname": "Tester8",
    "password": "12345"
}

### 받은 토큰 예시 
### TESTER1 : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1OTI1NTQxN30.VyUmRuWnfqSu_aUx6Dcn09vTb58PDzKcUr6wRe8tXbE

### 게시글 작성 셍성 
POST http://nodeapi.myspaceti.me:8000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY1OTI1NTQ3MH0.WOd9z53hV97e82x3W3ISP_K0lktxaXjRJx_IKizxIn8

{
    "title": "안녕하세요22",
    "content": "이런저런 글입니다24444 안녕히계세요~~"
}
    
    
### 게시글 모두 조회 불러오는 (주소창)
GET http://nodeapi.myspaceti.me:8000/api/posts

### 특정 게시글 상세 조회
GET http://nodeapi.myspaceti.me:8000/api/posts/15

### 게시글 수정 
PUT http://nodeapi.myspaceti.me:8000/api/posts/15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1OTEwNzkzN30.GhUqUcTkokIY2N9gd99VXI1dkon8YZsThg_GocMce_E

{ 
    "title": "안녕하세요3",
    "content": "안녕하세요 게시글 수정합니당~."
}

### 게시글 삭제
DELETE http://nodeapi.myspaceti.me:8000/api/posts/15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1OTEwNzkzN30.GhUqUcTkokIY2N9gd99VXI1dkon8YZsThg_GocMce_E


### 게시글 좋아요
PUT http://nodeapi.myspaceti.me:8000/api/posts/15/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY1OTA5MTgxOH0.ncec1VIJSVh6vDGVDsdl3lCoFw7dmSPR_YupAE9yGTg


### 사용자가 좋아한 게시글 리스트
GET http://nodeapi.myspaceti.me:8000/api/posts/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY1OTA5MTgxOH0.ncec1VIJSVh6vDGVDsdl3lCoFw7dmSPR_YupAE9yGTg

#################### Comments ########################

### 특정 게시글에 댓글 작성   // 사용중인 유저로 진행 필요
POST http://nodeapi.myspaceti.me:8000/api/comments/15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1OTEwNzkzN30.GhUqUcTkokIY2N9gd99VXI1dkon8YZsThg_GocMce_E

{
    "comment": "안녕하세요 댓글입니다."
}
    
### 특정 게시글의 댓글 조회
GET http://nodeapi.myspaceti.me:8000/api/comments/15

### 댓글 수정
PUT http://nodeapi.myspaceti.me:8000/api/comments/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1OTEwNzkzN30.GhUqUcTkokIY2N9gd99VXI1dkon8YZsThg_GocMce_E

{ 
    "comment": "안녕하세요 수정된 댓글입니다."
}


### 댓글 삭제 
DELETE http://nodeapi.myspaceti.me:8000/api/comments/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1OTEwNzkzN30.GhUqUcTkokIY2N9gd99VXI1dkon8YZsThg_GocMce_E