# @host = https://api.tube-tuning.com
# @host = https://tube-tuning.com
@host = http://localhost:4000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0xvZ2luIjp0cnVlLCJ1c2VyX2lkIjoiNjMyOTk0MDhmZDFkNmMyYWM0MWQ2NGM1IiwiYWNjZXNzVG9rZW4iOiJ5YTI5LmEwQWE0eHJYTV9IaVNCRmM4RkR1WmFQREQzbVZSTG9TdHJ0aTFhSWs0Y1E4Z3NGOTl3SEJaaVQzcGRMOHlOMFU3U2FkNHFnS3pYQTJQcmpza09LTkdCWFNaeVBlYmJ0YnVzWVBBajU0T05sd0haSUo0ZENzdm9KQkF0WWF4ZDFTVW8tRk5TY1ZwRmlIRFVrVlZlcjZJV0x0ZU9jZ18zU0FhQ2dZS0FUQVNBUkVTRlFFakR2TDlIN09qemN0a25pYmxvdkQxSEktZXpnMDE2NSIsImlhdCI6MTY2NDc2NDY2NiwiZXhwIjoxNjY0ODUxMDY2fQ.UTmxuecC1AR5IYgbBYyRh_7VeWeVWw9ko22eCBhjD1w

# 만료 토큰
# @token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0xvZ2luIjp0cnVlLCJ1c2VyX2lkIjoiNjMyOTk0MDhmZDFkNmMyYWM0MWQ2NGM1IiwiYWNjZXNzVG9rZW4iOiJ5YTI5LmEwQWE0eHJYTkhZR3pfdHJqTV9QRC1JNU9ScWQwVzZJVHRCXzdadTFxbUJKSnhGbzBJdDQ5LVljejhNUHhKU3FqV1ZHN0JVbFBLU0tiVm1NUXExVDdjZEpxb0lfWDZQNHpTd3JTYUN0c2NwYzdpYTNGR2ZaS096MjRPczJJanRPRWFVc193WnF0X3lkWnlFX3ByQVpaX1VWSUUzX0EycWdhQ2dZS0FUQVNBUkVTRlFFakR2TDlEdUJxMkRLdnpRYU1SQjctMFpvWFl3MDE2NSIsImlhdCI6MTY2NDU1MDgyNCwiZXhwIjoxNjY0NjM3MjI0fQ.4CgeycE-ImES71Tx0-GBcM7hqsGL0UQ-dyurmi_d_Bg


### 오늘의 메인 추천 리셋하기
PUT {{host}}/api/collections/today

### 크롤링 유튜브 서버 1091, 1168
GET {{host}}/youtubesearch?q=bts

### 1. 카테고리 요소의 리스트 찾아오기 : GET /api/categories (60, 48, 57, 64) 57,53,38
GET	{{host}}/api/categories

### 2. 컬렉션 생성 : POST /api/collections
POST {{host}}/api/collections
Content-Type: application/json
Authorization: {{token}}

{
    "category_id": "6319aeebd1e330e86bbade88",
    "collectionTitle": "생성 테스트하기",
    "description": "ㅇㅇ",
    "videos": ["_VE04NqHNqc",
  "P1UZTj1h1a0",
  "hKfb-rudyWA",
  "JdHyjfVcN9Y",
  "rRhowWJ6r_4",
  "8z_HtjtIdio",
  "lmmA-go5244",
  "wunMxN8LTV8"],
    "isVisible": "true"
}


### 3. 특정 컬렉션 id로 상세정보 : GET /api/collections/:collection_id (137, 218) -> 59, 68,63
GET	{{host}}/api/collections/63326323993a78c1c2ca23e1

### 4. 특정 컬렉션 id로 삭제하기 : DELETE /api/collections/:collection_id
DELETE {{host}}/api/collections/63314649f110a6e90341c232

### 5. DB에 올려진 특정 영상(id 배열)들을 받아 컬렉션에 추가하기 : PUT /api/collections/:collection_id
PUT	{{host}}/api/collections/63314840ad4a58f54fe0c5af
Content-Type: application/json
Authorization: {{token}}

{
    "videos": ["6312c7b4d3084a7cb866bb8f", "6312c7b4d3084a7cb866bb95"]
}

### 6. 특정 id 컬렉션에 좋아요 누르기 (이미 좋아한 적 있으면 취소됨): PUT /api/collections/like/:collection_id
PUT	{{host}}/api/collections/like/63291a3fdcc97f368cc4fe92
Authorization: {{token}}

### 6. 컬렉션 담기/담기 취소
PUT {{host}}/api/collections/keep/6332632d993a78c1c2ca24b9
Authorization: {{token}}

### 7. 내가 좋아한 컬렉션 리스트 : GET /api/collections/mylikes (93, 78) -> 66, 71
GET	{{host}}/api/collections/mylikes?offset=0&limit=5
Content-Type: application/json
Authorization: {{token}}

### 7. 내가 담은 컬렉션 리스트 : GET /api/collections/mykeeps (79, 52) -> 55, 58
GET	{{host}}/api/collections/mykeeps?offset=0&limit=5
Content-Type: application/json
Authorization: {{token}}

### 7. 내가 생성한 컬렉션 리스트 : GET /api/collections/mine (82, 67) -> 62,52
GET	{{host}}/api/collections/mine?offset=0&limit=5
Content-Type: application/json
Authorization: {{token}}

### 8. 카테고리에 맞는 컬렉션 리스트 찾기 : GET /api/collections?category_id= (63,112) -> 42, 47, 51
GET	{{host}}/api/collections?category_id=6319aeebd1e330e86bbade7c&offset=0&limit=3


### 9. 검색어에 맞는 컬렉션 리스트 찾기 : GET /api/collections?keyword= (159, 137, 117) -> 90, 124,75,86
GET	{{host}}/api/collections/search?keyword=BTS&offset=0&limit=2

### 10. collection_id 컬렉션에 달린 댓글 리스트 보기 : GET /api/comments/:collection_id (77, 66) -> 56,57
GET	{{host}}/api/comments/6332632d993a78c1c2ca24b9

### 11. collection_id 컬렉션에 댓글 달기  : POST /api/comments/:collection_id
POST {{host}}/api/comments/633a761026c46d7df977deb0
Content-Type: application/json
Authorization: {{token}}

{
   "comment" : "너덜트 너무 재밌어요!"
}

### 12. 특정 id를 가진 댓글을 수정하기  : PUT /api/comments/:collection_id (50, 42)
PUT	{{host}}/api/comments/6336eafe4c3d6b09fea6db66
Content-Type: application/json
Authorization: {{token}}

{
   "comment" : "너무 좋아요!!"
}

### 13. 특정 id를 가진 댓글을 삭제하기  : DELETE /api/comments/:collection_id
DELETE {{host}}/api/comments/6336eafe4c3d6b09fea6db66
Authorization: {{token}}

### 13. 특정 id를 가진 댓글을 좋아요/좋아요 취소  : PUT /api/comments/:collection_id
PUT	{{host}}/api/comments/like/6332632d993a78c1c2ca24b9
Authorization: {{token}}

### NOT USED 14. (기본찾기) 우리DB에 저장된 영상 중에 검색하기 : GET /api/search/videos/db?keyword=
GET {{host}}/api/search/videos/db?keyword=축구

### NOT USED 15. (더찾아보기) 유튜브API에 100점 주고 검색하기 : GET /api/search/videos/youtube?keyword=
GET {{host}}/api/search/videos/youtube?keyword=축구

### 16. 로그인한 유저의 정보 가져오기 : GET /api/user (43,56) -> 41,52
GET	{{host}}/api/user/
Authorization: {{token}}

### 17. 고유 id로 유저 정보 찾기 : GET /api/user/:user_id (67,42) -> 53, 52
GET {{host}}/api/user/632919bd0c70d67f1b92e012

### 18. 특정 id 컬렉션에 포함되어 있는 영상들의 리스트 : GET /api/videos/:collection_id (61,69)->50,59,68
GET	{{host}}/api/videos/6332632d993a78c1c2ca24b9?offset=0&limit=2

### 19. 특정 id 영상의 더 상세한 정보 불러오기 : GET /api/videos/detail/:video_id (271,236)-> 272, 293, 252
GET	{{host}}/api/videos/detail/6332632d993a78c1c2ca248a


### NOT USED 21. 유튜브영상의 고유 videoId(우리 DB의 영상_id 아님)로 유튜브 썸네일 등 상세정보 찾기
GET	https://www.googleapis.com/youtube/v3/videos?key=AIzaSyBJg1gJLZT0As7NGbFDHpWFLO_mi4JDw0c&part=snippet&maxResults=50&regionCode=kr&id=PZIPsKgWJiw

### 24. 특정 컬렉션 id로 수정하기 : PUT /api/collections/:collection_id 
PUT {{host}}/api/collections/6332632d993a78c1c2ca248a
Content-Type: application/json
Authorization: {{token}}

{
    "category_id": "6319aeebd1e330e86bbade88",
    "collectionTitle": "mbti 수정",
    "description": "mbti 신기행",
    "videos": ["5yiMd2lGQJo", "PmGs8I7qetY"]
}

### 25. PUT	/api/user/interest/:category_id  _ 관심사 카테고리 선택
PUT {{host}}/api/user/interest/6319aeebd1e330e86bbade80,6319aeebd1e330e86bbade89
Authorization: {{token}}

### 26. GET	/api/user/interest/  _ 관심사 카테고리 불러오기 (로그인유저) 52,60
GET {{host}}/api/user/interest
Authorization: {{token}}

### 27. DELETE	/api/user/interest/:category_id  _ 관심사 카테고리 제거하기 (로그인유저)
DELETE {{host}}/api/user/interest/6319aeebd1e330e86bbade7c
Authorization: {{token}}

### 28. PUT	/api/user/keep/:collection_id  _ 로그인유저 컬렉션 담기
PUT {{host}}/api/user/keep/63291a3fdcc97f368cc4fe92
Authorization: {{token}}

### 29. DELETE	/api/user/keep/:collection_id  _ 로그인유저 컬렉션 담기 취소
DELETE {{host}}/api/user/keep/63291a3fdcc97f368cc4fe92
Authorization: {{token}}

### 30. GET	/api/user/keep/:collection_id  _ 로그인유저 담기 컬렉션 조회 87,60 -> 56,88,55
GET {{host}}/api/user/keep
Authorization: {{token}}

### 31. GET	/api/collections/whokeep/:collection_id  _ 컬렉션을 담은 이용자 리스트 조회 54,71 -> 63,50
GET {{host}}/api/collections/whokeep/63330f662798150917d3f376

### 32. 로그인 유저가 params 유저를 팔로잉하기 49,52 -> 75,64
PUT {{host}}/api/user/follow/632919bf0c70d67f1b92e0e3
Authorization: {{token}}

### 33. params 유저가 팔로잉 하고 있는 유저들의 id 리스트 64, 83 -> 51,52
GET {{host}}/api/user/follow/632919bf0c70d67f1b92e0e3

### 34. 4가지 카테고리에 해당하는 컬렉션 정보 불러오기 172, 188 -> 157, 154
POST	{{host}}/api/collections/recommendation
Content-Type: application/json

{ 
    "category_ids" :
     ["6319aeebd1e330e86bbade9f", "631e7d7a4ae4c133c405a964", "631e7d7a4ae4c133c405a966", "631e7d7a4ae4c133c405a965"]
} 

### 35. 특정 컬렉션에서 영상을 제거하기
DELETE	{{host}}/api/collections/remove/63314840ad4a58f54fe0c5af?video_id=6312c7b4d3084a7cb866bb8f
Authorization: {{token}}

### 36. 특정 id 컬렉션 비공개 설정 누르기 (이미 비공개이면 공개로 변경)
PUT	{{host}}/api/collections/visible/63340c199de7258b72ad0538
Authorization: {{token}}

### 37. 특정 id 댓글에 좋아요 누르기 (이미 좋아한 적 있으면 취소됨): PUT /api/collections/like/:comment_id
PUT	{{host}}/api/comments/like/633267bca096ccc32f9af689
Authorization: {{token}}

### 38. 인기 키워드 n개 찾기 : GET /api/collections/search/frequent?limit= 55,42 -> 48,58
GET	{{host}}/api/collections/search/frequent?limit=10

###
GET https://www.googleapis.com/oauth2/v2/userinfo?access_token=ya29.a0Aa4xrXOYT6xVy4I0QCK3R6RdL15nE94ECy70LO9AKWu4VKccqCzKCWGSt0T4hQstPm6chuYweATQSxehKOfsaRjvO69Mrn5xnr6UWIYnwZlEwtwoPYGfcEfIj_bF-KqBXad5u7jka4T919zlLdM0X7jkz-NfZgaCgYKATASARESFQEjDvL9Wm_4zhZ1gKZ44OGqbVL-3Q0165&alt=json&prettyPrint=true