@host = https://tube-tuning.com

## ---------------------- 카테고리 관련 API ------------------------
### 1. 카테고리 요소의 리스트 찾아오기 : GET /api/categories
GET	{{host}}/api/categories





## ---------------------- 컬렉션 관련 API ------------------------

### 2. 컬렉션 생성 : POST /api/collections
POST {{host}}/api/collections
Content-Type: application/json

{
    "category_id": "6312c45c65fc44c5a50ee0e3",
    "collectionTitle": "내 게임 영상",
    "description": "롤 좋아요",
    "videos": ["cEwe79YQSqU",
        "GftRMtJ0"]
}


### 3. 특정 컬렉션 id로 상세정보 : GET /api/collections/:collection_id
GET	{{host}}/api/collections/6316eed7b34698b92f0224ea



### 4. 특정 컬렉션 id로 삭제하기 : DELETE /api/collections/:collection_id
DELETE {{host}}/api/collections/631594404d6491e5475fa1db

### 5. DB에 올려진 특정 영상(id 배열)들을 받아 컬렉션에 추가하기 : PUT /api/collections/:collection_id
PUT	{{host}}/api/collections/63136cbd25b3d37574b18bfd
Content-Type: application/json

{
    "videos": ["6312c7b4d3084a7cb866bb8f", "6312c7b4d3084a7cb866bb95"]
}


### 6. 특정 id 컬렉션에 좋아요 누르기 (이미 좋아한 적 있으면 취소됨): PUT /api/collections/like/:collection_id
PUT	{{host}}/api/collections/like/630f30fa71d6081b5c178ed1
Content-Type: application/json


### 7. 내가 생성한 컬렉션 리스트 : GET /api/collections/mine
GET	{{host}}/api/collections/mine?offset=4&limit=4
Content-Type: application/json


### 8. 카테고리에 맞는 컬렉션 리스트 찾기 : GET /api/collections?category_id=
GET	{{host}}/api/collections?category_id=6312c45c65fc44c5a50ee0e3&offset=0&limit=3


### 9. 검색어에 맞는 컬렉션 리스트 찾기 : GET /api/collections?keyword=
GET	{{host}}/api/collections/search?keyword=음악&offset=0&limit=3







## ---------------------- 컬렉션에 달린 댓글 관련 API ------------------------

### 10. collection_id 컬렉션에 달린 댓글 리스트 보기 : GET /api/comments/:collection_id
GET	{{host}}/api/comments/6316eed7b34698b92f0224ea


### 11. collection_id 컬렉션에 댓글 달기  : POST /api/comments/:collection_id
POST {{host}}/api/comments/6316eed7b34698b92f0224ea
Content-Type: application/json

{
   "comment" : "오 짱!!"
}

### 12. 특정 id를 가진 댓글을 수정하기  : PUT /api/comments/:collection_id
PUT	{{host}}/api/comments/63136b9625b3d37574b18bee
Content-Type: application/json

{
   "comment" : "레알 진짜 짱 좋아요 짱짱짱 !"
}


### 13. 특정 id를 가진 댓글을 삭제하기  : DELETE /api/comments/:collection_id
DELETE {{host}}/api/comments/63136b9625b3d37574b18bee





## ---------------------- 영상 찾기 관련 API ------------------------
### 14. (기본찾기) 우리DB에 저장된 영상 중에 검색하기 : GET /api/search/videos/db?keyword=
GET {{host}}/api/search/videos/db?keyword=디자인


### 15. (더찾아보기) 유튜브API에 100점 주고 검색하기 : GET /api/search/videos/youtube?keyword=
GET {{host}}/api/search/videos/youtube?keyword=운동





## ---------------------- 유저 정보 찾기 관련 API ------------------------
### 16. 로그인한 유저의 정보 가져오기 : GET /api/user
GET	{{host}}/api/user/


### 17. 고유 id로 유저 정보 찾기 : GET /api/user/:user_id
GET {{host}}/api/user/6312ad8b5057863778c220ca





## ---------------------- 영상 관련 API  ------------------------
### 18. 특정 id 컬렉션에 포함되어 있는 영상들의 리스트 : GET /api/videos/:collection_id
GET	{{host}}/api/videos/6312cd792a4f77334033a9be?offset=3&limit=3


### 19. 특정 id 영상의 더 상세한 정보 불러오기 : GET /api/videos/detail/:video_id
GET	{{host}}/api/videos/detail/6316ed250e31df6d8ef56c37


### 21. 유튜브영상의 고유 videoId(우리 DB의 영상_id 아님)로 유튜브 썸네일 등 상세정보 찾기
### 유튜브API 직접 접근 (맨 뒤에 PZIPsKgWJiw만 유튜브 고유 번호로 변경) 
GET	https://www.googleapis.com/youtube/v3/videos?key=AIzaSyBJg1gJLZT0As7NGbFDHpWFLO_mi4JDw0c&part=snippet&maxResults=50&regionCode=kr&id=PZIPsKgWJiw


### 22. 영상 아이디를 하나 넣으면 그 채널 전체의 재생목록 영상을 검색가능하게 함
POST {{host}}/api/videos/add/FPkrJjDO7Fc
