
## ---------------------- 카테고리 관련 API (승민 님) ------------------------
### 카테고리 요소의 리스트 찾아오기 <완료>
GET	https://localhost/api/categories

## ---------------------- 컬렉션에 달린 댓글 관련 API (승민 님) ------------------------
### collection_id 컬렉션에 댓글 달기  <완료 (유저 빼고)>
POST https://localhost/api/comments/631379b35d4d531007077cf2
Content-Type: application/json

{
   "comment" : "나는 동의하지 않습니다!"
}

### collection_id 컬렉션에 달린 댓글 리스트 보기  <완료>
GET	https://localhost/api/comments/630f30fa71d6081b5c178ecf


### 특정 id를 가진 댓글을 수정하기  <완료>
PUT	https://localhost/api/comments/6311e1d03fc3cf644036b5f4
Content-Type: application/json

{
   "comment" : "나는 쬐끔 동의하지 않습니다!"
}


### 특정 id를 가진 댓글을 삭제하기  <완료>
DELETE https://localhost/api/comments/630f31258b8c916480f96adc



## ---------------------- 영상 관련 API (승민 님) ------------------------
### 특정 id 컬렉션의 영상들의 리스트 불러오기   <완료>
GET	https://localhost/api/videos/630f30fa71d6081b5c178ed2


### 특정 id 영상의 디테일한 정보를 불러오기   <완료>
GET	https://localhost/api/videos/detail/6311f30092124ed948276547


## ---------------------- 컬렉션 관련 API (혜미 님) ------------------------

### 컬렉션 생성 <완료>
POST https://localhost/api/collections
Content-Type: application/json

{
    "category_id": "6312c45c65fc44c5a50ee0e4",
    "collectionTitle": "동기부여 영상",
    "description": "동기부여 빡!",
    "videos": ["6312c7b4d3084a7cb866bb97", "6312c7b4d3084a7cb866bb98", "6312c7b4d3084a7cb866bb9b"]
}

### 특정 id의 컬렉션 상세정보 <완료>
GET	https://localhost/api/collections/6312fa34273948ffb061a431



### 카테고리에 맞는 컬렉션 리스트 찾기 <완료>
GET	https://localhost/api/collections?category_id=6312c45c65fc44c5a50ee0e4


### 검색어에 맞는 컬렉션 리스트 찾기 <완료>
GET	https://localhost/api/collections/search?keyword=음악


### 특정 id 컬렉션 삭제하기 <완료>
DELETE https://localhost/api/collections/631379b35d4d531007077cf2
Content-Type: application/json


### 내가 만든 컬렉션 리스트 <완료>
GET	https://localhost/api/collections/mine
Content-Type: application/json


### 특정 id의 컬렉션에 좋아요 누르기 (이미 좋아한 적 있으면 취소) <완료>
PUT	https://localhost/api/collections/like/6312f820273948ffb061a425
Content-Type: application/json


### 특정 id의 컬렉션에 영상 추가하기 <완료>
PUT	https://localhost/api/collections/6312f820273948ffb061a425
Content-Type: application/json

{
    "videos": ["6311f30092124ed94827654e", "6311f30092124ed94827654d"]
}


### 유저 정보 찾기 
GET https://localhost/api/user/630f6bda3e3cc41e4f320ff1

### 로그인한 유저 정보 찾기
GET	https://localhost/api/user/




## ---------------------- 영상 찾기 관련 API (보현) ------------------------
### (기본찾기) 운동이라는 키워드 - videoSearchDB에서 찾기
GET https://localhost/api/search/videos/db?keyword=노래


### (더찾아보기) 운동이라는 키워드 유튜브API에서 찾기
GET https://localhost/api/search/videos/youtube?keyword=운동

