name: remote ssh command for deploy
on:
  push:
    branches: [main]

#
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_EC2 }}
          username: ${{ secrets.USER_EC2 }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: ./deploy.sh
